"""Column-level coverage stats for interim / processed parquet files.

We measure two things per column:

  * **fill rate** — fraction of rows where the column is non-null and non-empty.
  * **distinct count** — how many distinct non-null values the column carries.

These are the cheapest possible signals that "did ingestion actually
populate this field, or is it secretly all-null?" without doing any
domain-aware validation.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import polars as pl


@dataclass(frozen=True)
class ColumnCoverage:
    column: str
    dtype: str
    rows: int
    non_null: int
    non_empty: int
    distinct: int

    @property
    def fill_rate(self) -> float:
        return 0.0 if self.rows == 0 else self.non_empty / self.rows


def coverage_for(df: pl.DataFrame) -> list[ColumnCoverage]:
    """Return per-column coverage stats for ``df``."""
    out: list[ColumnCoverage] = []
    n = df.height
    for col, dtype in zip(df.columns, df.dtypes, strict=True):
        s = df[col]
        non_null = int(s.is_not_null().sum())
        if dtype == pl.Utf8:
            non_empty = int((s.fill_null("").str.len_chars() > 0).sum())
        else:
            non_empty = non_null
        distinct = int(s.n_unique()) - (0 if non_null == n else 1)  # ignore the null bucket
        out.append(
            ColumnCoverage(
                column=col,
                dtype=str(dtype),
                rows=n,
                non_null=non_null,
                non_empty=non_empty,
                distinct=max(distinct, 0),
            )
        )
    return out


def coverage_table_markdown(stats: list[ColumnCoverage]) -> str:
    """Render the per-column stats as a Markdown table."""
    lines = [
        "| Column | Type | Rows | Non-empty | Fill rate | Distinct |",
        "| --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for s in stats:
        lines.append(
            f"| `{s.column}` | {s.dtype} | {s.rows} | {s.non_empty} | "
            f"{s.fill_rate:.1%} | {s.distinct} |"
        )
    return "\n".join(lines)


def render_report(parquet_paths: list[Path]) -> str:
    """Build a full multi-file Markdown coverage report."""
    sections: list[str] = [
        "# Coverage report",
        "",
        "Generated by `scripts/coverage_report.py`. Fill rate is "
        "(non-null and non-empty) / total rows.",
        "",
    ]
    for path in parquet_paths:
        if not path.exists():
            sections.append(f"## `{path.name}` — _missing_\n")
            continue
        df = pl.read_parquet(path)
        stats = coverage_for(df)
        sections.append(f"## `{path.name}` — {df.height:,} rows")
        sections.append("")
        sections.append(coverage_table_markdown(stats))
        sections.append("")
    return "\n".join(sections).rstrip() + "\n"
